### ISSUE TITLE
Homebrew formula is not up-to-date

### ISSUE THREAD

**Issue by fharper** [kcrawford/dockutil#146]
dockutil on Homebrew is the 2.0.5 version, which is more than six years old. At the moment of creating this issue, v3.0.2 is the latest version.

**Comment by phinze** [comment]
👋 I just read through the relevant backlog trying to figure out what's up. It looks like [Homebrew is blocked](https://github.com/Homebrew/homebrew-core/pull/97394) until #131 is merged so the package can be built.

Unfortunately, there's been no word from @kcrawford since Mar 2022, so Homebrew might have to [deprecate the formula](https://github.com/Homebrew/homebrew-core/pull/123067).

**Comment by kcrawford** [comment]
Why can’t homebrew explode the pkg and extract the binary? Why would you want to build it from source? Binary is signed.

**Comment by SMillerDev** [comment]
> Why would you want to build it from source?

Because that's a requirement to be included in Homebrew. All Homebrew formula are build from source.

**Comment by phinze** [comment]
Hi @kcrawford - thanks for taking the time to look at this.

If you're open to accepting #131 that should resolve the issue with Homebrew.

If you'd prefer not to accept that PR, Homebrew does have a way of installing binary packages. It calls these packages Casks instead of Formulae. However, the maintainers prefer to have Formula for cli-only open source packages, as suggested by [this comment on a past (rejected) attempt to submit dockutil as a Cask](https://github.com/Homebrew/homebrew-cask/pull/125996#issuecomment-1159444206). We can try to appeal that decision if you are against the linked PR.

Let me know your thoughts and I'll try and keep the linked Homebrew issues up to date with the news.

**Comment by jsardev** [comment]
I see https://github.com/kcrawford/dockutil/pull/131 has been merged - can we do something with this issue? 🤔🙏

**Comment by kcrawford** [comment]
I think homebrew formula maintainers should have what they need now.  (SPM, license, release)

**Comment by straxhaber** [comment]
Thank you @kcrawford!

**Comment by fharper** [comment]
Do we know who is maintaining this Homebrew formula?
